name: Pull requests check

on:
  - pull_request

jobs:
  build:
    name: Lint & Test build
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        env:
          HUSKY: 0
        run: npm ci
      - name: Lint
        run: npm run lint:check
      - name: Format
        run: npm run format:check
      - name: Build
        run: npm run build
      - name: Tests
        run: npm run test
      - name: Set commit status
        uses: myrotvorets/set-commit-status-action@master
        # Always run this even if previous steps fail
        if: always()
        with:
          status: ${{ job.status }}
          sha: ${{ github.sha }}
